{
 "title": "Services Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "services",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=\"application\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Memory Check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage $services",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "repeat": "services",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (label_replace(avg_over_time(container_memory_usage_bytes{namespace=\"application\",container!=\"\",pod=~\"^$services.*\"}[30s]), \"service\", \"$1\", \"pod\", \"^([^0-9]*)-(.*)\")) \r\n",
     "legendFormat": "current"
    },
    {
     "expr": "sum by (service) (label_replace(container_spec_memory_limit_bytes{namespace=\"application\",container!=\"\",pod=~\"^$services.*\"}, \"service\", \"$1\", \"pod\", \"^([^0-9]*)-(.*)\"))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage $services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
     "repeat": "services",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (service) (label_replace(avg_over_time(container_memory_usage_bytes{namespace=\"application\",container!=\"\",pod=~\"^$services.*\"}[30s]), \"service\", \"$1\", \"pod\", \"^([^0-9]*)-(.*)\"))\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu Usage $services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
     "repeat": "services",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (service) (label_replace(rate(container_cpu_usage_seconds_total{namespace=\"application\",container!=\"\",pod=~\"^$services.*\"}[30s]), \"service\", \"$1\", \"pod\", \"^([^0-9]*)-(.*)\"))\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Global Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (service) (label_replace(avg_over_time(container_memory_usage_bytes{namespace=\"application\",container!=\"\"}[30s]), \"service\", \"$1\", \"pod\", \"^([^0-9]*)-(.*)\"))\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (service) (label_replace(rate(container_cpu_usage_seconds_total{namespace=\"application\",container!=\"\"}[1m]), \"service\", \"$1\", \"pod\", \"^([^0-9]*)-(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}