{
 "title": "stock files",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pharmacy",
    "query": "select pharmacy_lgo.pharmacy_id as __value, pharmacy_lgo.pharmacy_v2_id as __text from pharmacy_lgo order by pharmacy_lgo.pharmacy_v2_id;"
   },
   {
    "name": "lgo",
    "query": "select lgo_name from pharmacy_lgo group by lgo_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Latence",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pharmanity_stock_v1_latency_seconds",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "pharmanity_stock_v2_latency_seconds",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "pharmanity_stock_file_v2_latency_seconds",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "fichiers créés par heure",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(f.file_date, '1h'),\n  COUNT(f.*) AS file_count\nFROM stock_file f\n  JOIN pharmacy_lgo l ON f.pharmacy_id=l.pharmacy_id\nWHERE \n  $__timeFilter(f.file_date)\n  and f.pharmacy_id IN(${pharmacy})\n  and l.lgo_name IN(${lgo})\nGROUP BY\n  time\n "
    }
   ]
  },
  {
   "title": "Stock files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \n  $__time(f.file_date),\n  EXTRACT(EPOCH FROM (f.processed_date - f.fetched_at)) AS process_time \nFROM stock_file f\n  JOIN pharmacy_lgo l ON f.pharmacy_id=l.pharmacy_id\nWHERE \n  $__timeFilter(f.file_date)\n  and f.error_message is null\n  and f.pharmacy_id IN(${pharmacy})\n  and l.lgo_name IN(${lgo})\n  and f.processed_date is not null \n  and f.fetched_at is not null\n "
    },
    {
     "rawSql": "SELECT \n  $__timeGroup(f.file_date, '60s'),\n  COUNT(*) AS error_count \nFROM stock_file f\n  JOIN pharmacy_lgo l ON f.pharmacy_id=l.pharmacy_id\nWHERE $__timeFilter(f.file_date) \n  and f.pharmacy_id IN(${pharmacy})\n  and l.lgo_name IN(${lgo})\n  and f.error_message is not null\nGROUP BY time\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(f.file_date, '60s'),\n  COUNT(*) AS waiting_count\nFROM\n  stock_file f\n  JOIN pharmacy_lgo l ON f.pharmacy_id=l.pharmacy_id\nWHERE\n  $__timeFilter(f.file_date)\n  and f.pharmacy_id IN(${pharmacy})\n  and l.lgo_name IN(${lgo})\n  and f.processed_date is null\nGROUP BY\n  time\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(f.file_date, '60s'),\n  COUNT(*) AS success_count\nFROM\n  stock_file f\n  JOIN pharmacy_lgo l ON f.pharmacy_id=l.pharmacy_id\nWHERE\n  $__timeFilter(f.file_date)\n  and f.pharmacy_id IN(${pharmacy})\n  and l.lgo_name IN(${lgo})\n  and f.processed_date is not null and error_message is null\nGROUP BY\n  time"
    }
   ]
  },
  {
   "title": "Tous les fichiers",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT \n  f.file_date,\n  p.pharmacy_id,\n  p.pharmacy_v2_id ,\n  p.lgo_name,\n  f.error_message,\n  f.service_origin,\n  (date_trunc('second', f.processed_date) - date_trunc('second', f.fetched_at)) as process_time,\n  f.stock_creations as creations,\n  f.stock_updates as updates\nFROM stock_file f\n  JOIN pharmacy_lgo p ON f.pharmacy_id=p.pharmacy_id\nWHERE \n  $__timeFilter(f.file_date)\n  and p.pharmacy_id IN(${pharmacy})\n  and p.lgo_name IN(${lgo})\nORDER BY f.file_date desc"
    }
   ]
  }
 ]
}