{
 "title": "Pharmacies stock updates",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Mises à jour de la table pharmacy_presentations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(pp.updated_at, '5s'),\n  COUNT(pp.stock) as value,\n  p.name as metric \nFROM\n  pharmacy_presentations pp\n    JOIN pharmacies p ON p.id=pp.pharmacy_id\nWHERE $__timeFilter(pp.updated_at) \nGROUP BY p.name, time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Par flux",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  l.flux as metric, \n  COUNT(pp.stock) as value\nFROM\n  pharmacy_presentations pp\n    JOIN pharmacies p ON p.id=pp.pharmacy_id\n    JOIN lgos l ON l.pharmacy_id=p.id\nWHERE $__timeFilter(pp.updated_at) \nGROUP BY l.flux"
    }
   ]
  },
  {
   "title": "Par LGO",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  l.name as metric, \n  COUNT(pp.stock) as value\nFROM\n  pharmacy_presentations pp\n    JOIN pharmacies p ON p.id=pp.pharmacy_id\n    JOIN lgos l ON l.pharmacy_id=p.id\nWHERE $__timeFilter(pp.updated_at) \nGROUP BY l.name"
    }
   ]
  }
 ]
}