{
 "title": "synchro",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "last stock file",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pharmanity_staging",
     "rawSql": "select max(processed_at) as v2 from stock_file;"
    },
    {
     "rawSql": "select max(processed_date) as v3 from stock_file;"
    }
   ]
  },
  {
   "title": "last stock",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pharmanity_staging",
     "rawSql": "select max(update_at) as v2 from pharmacie_presentation;"
    },
    {
     "rawSql": "select max(updated_at) as v3 from pharmacy_presentations;"
    },
    {
     "dataset": "pharmanity_staging",
     "rawSql": "select max(updated_at) as v1 from ph_pres"
    }
   ]
  },
  {
   "title": "pharmacy LGO",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pharmanity_staging",
     "rawSql": "select max(created_at) as v2 from user_lgo;"
    },
    {
     "rawSql": "select max(created_at) as v3 from pharmacy_lgo;"
    }
   ]
  }
 ]
}